### ISSUE TITLE
husarnet-dds singleshot "/usr/local/bin/husarnet-dds: line 1: Not: command not found" error

### ISSUE THREAD

**Issue by CamRW** [husarnet/husarnet-dds#1]
I'm having an issue getting the bare minimum working here...

Commands I ran:

RELEASE="v1.0.10"
ARCH="amd64"

sudo curl -L https://github.com/husarnet/husarnet-dds/releases/download/$RELEASE/husarnet-dds-linux-$ARCH -o /usr/local/bin/husarnet-dds
sudo chmod +x /usr/local/bin/husarnet-dds

No issues yet... It does create the binary in the correct location and gives it executable permissions. Next I run all in one terminal:

export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export FASTRTPS_DEFAULT_PROFILES_FILE=./husarnet-fastdds-simple.xml
husarnet-dds singleshot

On the husarnet-dds singleshot command I get the error:

"/usr/local/bin/husarnet-dds: line 1: Not: command not found"

I tried logging in and out and specifying the full path to the executable to ensure it's being called correctly. Maybe I'm missing something obvious I'm unaware of? I believe the expected behavior is to create a DDS profile automatically configured for Husarnet. I appreciate the help :)

Running directly on my host OS (no container), Ubuntu 20.04

**Comment by DominikN** [comment]
Hi @CamRW , there is no `"v1.0.10"` release available. Please use the latest one - `v1.2.1`: https://github.com/husarnet/husarnet-dds/releases/tag/v1.2.1

**Comment by CamRW** [comment]
I knew it was something obvious! Thank you.
