### ISSUE TITLE
FastRTPS profile generated does not show ros topics on local machine or remote machine

### ISSUE THREAD

**Issue by CamRW** [husarnet/husarnet-dds#2]
I'm having an issue after starting from scratch with husarnet and husarnet-dds. I can't see any topics published on my local machine or my remote machine. My process is as follows for setting up my FastRTPS custom profile, the same steps are used on both machines.

# Husarnet Version:
● CLI:                                  2.0.78
● Daemon (running):          2.0.78
● Daemon (binary):            2.0.78

# Husarnet-dds Version:

husarnet-dds | v1.3.4

# Husarnet Setup Process:

-   Install Husarnet (using apt on both machines)
-   Add machines to the network
-   Ping machines (just to confirm they can communicate, they are also visible in the dashboard and with the CLI tool with no errors)

# Husarnet-dds Setup:

- Install the tool (no errors)
```bash
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export FASTRTPS_DEFAULT_PROFILES_FILE=/full/path/to/xml/husarnet-fastdds-simple.xml
husarnet-dds singleshot
```

# Testing the Setup

Using that generated xml, I open two terminals on the same computer and run:
```bash
export FASTRTPS_DEFAULT_PROFILES_FILE=/full/path/to/xml/husarnet-fastdds-simple.xml
ros2 run demo_nodes_cpp talker
```

The talker is publishing normally

In the other terminal:
```bash
export FASTRTPS_DEFAULT_PROFILES_FILE=/full/path/to/xml/husarnet-fastdds-simple.xml
ros2 topic list
```

My output from ros2 topic list is:
/parameter_events
/rosout

I'm expecting to see a /chatter topic but when I use my custom dds profile, I get nothing. I've included my profile below, replacing my IPs with placeholders
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<dds>
  <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <transport_descriptors>
      <transport_descriptor>
        <transport_id>udpv6_transport</transport_id>
        <type>UDPv6</type>
        <maxInitialPeersRange>40</maxInitialPeersRange>
        <!-- <non_blocking_send>true</non_blocking_send> -->
      </transport_descriptor>
    </transport_descriptors>
    <participant profile_name="husarnet_simple_profile" is_default_profile="true">
      <rtps>
        <userTransports>
          <transport_id>udpv6_transport</transport_id>
        </userTransports>
        <useBuiltinTransports>true</useBuiltinTransports>
        <defaultUnicastLocatorList>
          <locator>
            <udpv6>
              <address>address-of-this-computer</address>
            </udpv6>
          </locator>
        </defaultUnicastLocatorList>
        <builtin>
          <initialPeersList>
            <locator>
              <udpv6>
                <address>address-of-this-computer</address>
              </udpv6>
            </locator>
            <locator>
              <udpv6>
                <address>address-of-other-computer</address>
              </udpv6>
            </locator>
            <locator>
              <udpv6>
                <address>address-of-this-computer</address>
              </udpv6>
            </locator>
          </initialPeersList>
          <metatrafficUnicastLocatorList>
            <locator>
              <udpv6>
                <address>address-of-this-computer</address>
              </udpv6>
            </locator>
          </metatrafficUnicastLocatorList>
        </builtin>
      </rtps>
    </participant>
  </profiles>
</dds>
```

Interestingly, this used to work, so I'm at a loss. I've tried editing some of the fields (changing builtin transports to false, changing the ordering in the initial peers list, etc) but no luck... Any help is appreciated!!

**Comment by DominikN** [comment]
Hi, 

please ensure that when launching the ROS nodes in the terminal, you have the RMW_IMPLEMENTATION set to rmw_fastrtps_cpp. If not, follow these steps:

1. Export environment variables each time you launch ROS nodes:
```bash
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export FASTRTPS_DEFAULT_PROFILES_FILE=/full/path/to/xml/husarnet-fastdds-simple.xml
ros2 run demo_nodes_cpp talker
```

or ...

2. Update `.bashrc` file:

```bash
echo "export RMW_IMPLEMENTATION=rmw_fastrtps_cpp" >> ~/.bashrc
echo "export FASTRTPS_DEFAULT_PROFILES_FILE=/full/path/to/xml/husarnet-fastdds-simple.xml" >> ~/.bashrc
source ~/.bashrc
```

After updating the .bashrc file, you can run ROS nodes without setting environment variables:

```bash
ros2 run demo_nodes_cpp talker
```

It is possible that it worked the first time because all environment variables were set correctly, but now you might be setting only the `FASTRTPS_DEFAULT_PROFILES_FILE`.

Please let me know about the results. Also please let me know what ROS 2 distro are you using.

**Comment by CamRW** [comment]
Hi DominikN,

Thanks for your quick response and your suggestions. I'm using Foxy, sorry for not mentioning that in the first post. I tried with  RMW_IMPLEMENTATION variable set to rmw_fastrtps_cpp but unfortunately still no luck.

Also running on Ubuntu 20.04 and exporting ROS_DOMAIN_ID=1 in both terminals, in case that helps.

**Comment by CamRW** [comment]
A bit of an update. My two machines within the VPN can see each other's topics, but both machines cannot see their own topics.

**Comment by DominikN** [comment]
Hi, could you please verify the functionality of the CycloneDDS configuration in your system? Additionally, I would appreciate it if you could display all the environment variables set in your system by executing the `printenv` command.

**Comment by CamRW** [comment]
Hi Dominik,

I tried with cyclonedds and had the same issue. I think something strange might be happening in the husarnet service but I am unsure. When I check the logs of husarnet.service with journalctl

I get this message:
WARNING  peer "IP-address" is not on the whitelist  (/app/core/peer_container.cpp:36)
WARNING  peer "IP-address" is not on the whitelist  (/app/core/peer_container.cpp:19)
It repeats quite a few times before outputting:
ERROR    tried to serialize unexpected peer to base message type: NAT_INIT_TRANSIENT (/app/core/ngsocket.cpp:848)

This IP is "almost" the local IP of the machine listed under the husarnet status tool and also on hnet0, but the last four values of the IPV6 address are replaced with 0001

For example if my IP address was 1111:2222:3333:4444:5555:6666:7777:8888
In the logs it's listed as 11112222333344445555666677770001

Additionally, when I run husarnet status
The localhost displays: 
inactive | no data flow | tunelled

Sorry I know I'm going off topic from the husarnet-dds tool and I can move this issue to husarnet issues if you think this behavior is unintended. I think I'll try a fresh install of husarnet (again) and see if that fixes anything.

**Comment by CamRW** [comment]
I wanted to update in order to close out this issue. 

Turns out there is some issue either between my setup or communication between ROS Foxy and ROS Humble. I decided to upgrade everything to Humble and run all instances within docker containers. After making the switch, the xml profile generated by husarnet-dds works. Thanks again for your time and help!
