### ISSUE TITLE
Husarnet daemon is unable to start

### ISSUE THREAD

**Issue by mr-fatcat** [husarnet/husarnet-dds#3]
After installation and reboot of Raspberry Pi (Ubuntu 22.04LTS), the husarnet deaemon is not able to start. 
![image](https://github.com/husarnet/husarnet-dds/assets/104271227/a4a3e55c-36e3-4d45-93eb-0bf73bcb371b)

If restarting husarnet daemon manually, an exit status 1 appears.
![image](https://github.com/husarnet/husarnet-dds/assets/104271227/74bdf41b-eca1-420b-aca8-a5d850ee2eba)

**Comment by fwlodarczyk** [comment]
Good morning @AndVdTij 👋 

Which version of Husarnet are you using?
Can you e-mail us Husarnet log file at [support@husarnet.com](mailto:support@husarnet.com)?
Make sure mention this Github issue in your e-mail.

To export logs use command:

```bash
sudo journalctl -u husarnet >> husarnet_log_AndVdTij.txt
```

Regards, Filip

**Comment by mr-fatcat** [comment]
Closing this issue as it's not the right repo for this
